name: Build React Native App for iOS and Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace kingdom_hall_attendant_mobile.xcworkspace \
                     -scheme kingdom_hall_attendant_mobile \
                     -configuration Release \
                     -derivedDataPath build

      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: ios/build/Build/Products/Release-iphoneos/

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set Up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradlew
        run: |
          cd android
          chmod +x ./gradlew

      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: android/app/build/outputs/apk/release/app-release.apk
