name: Build React Native App

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
      - name: Build iOS
        run: xcodebuild -workspace ios/kingdom_hall_attendant_mobile.xcworkspace -scheme kingdom_hall_attendant_mobile -sdk iphoneos -configuration Release archive -archivePath $PWD/build/kingdom_hall_attendant_mobile.xcarchive
      - name: Export .ipa
        run: xcodebuild -exportArchive -archivePath $PWD/build/kingdom_hall_attendant_mobile.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build
